[tools]
rust = "stable"
entire = "latest"
tombi = "latest"
"npm:openwiki" = "latest"
prek = "latest"
"pipx:commitizen" = "latest"
github-cli = "latest"

[env]
# RUST_LOG = "debug"

[settings]
minimum_release_age = "0d"

[tasks.test]
run = "cargo test"

[[watch_files]]
patterns = ["src/**/*.rs"]
run = "cargo fmt"
