[package]
name = "agm-registry"
version.workspace = true
edition.workspace = true

[dependencies]
agm-core = { workspace = true }
bytes = { workspace = true }
color-eyre = { workspace = true }
flate2 = { workspace = true }
http-body-util = { workspace = true }
octocrab = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
